kind: pipeline
type: docker
name: default

steps:
- name: Build Dependencies & Library
  image: rikorose/gcc-cmake
  commands:
  - git clone https://gitlab.com/libeigen/eigen.git
  - cd eigen
  - mkdir build
  - cd build
  - cmake .. > log.log
  - make install > log.log
  - cd ../..
  - mkdir build
  - cd build
  - cmake .. -DPYTHON=OFF -DEXAMPLES=OFF
  - make
- name: Test
  image: rikorose/gcc-cmake
  commands:
  - cd build
  - make test