kind: pipeline
type: docker
name: default

steps:
- name: Install Eigen
  image: rikorose/gcc-cmake
  commands:
  - git clone https://gitlab.com/libeigen/eigen.git
  - cd eigen
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install