kind: pipeline
type: docker
name: default

steps:
- name: Build Docker Image
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker build -t "${DRONE_REPO}:${DRONE_COMMIT:0:8}" .
  
- name: Build
  image: "${DRONE_REPO}:${DRONE_COMMIT:0:8}"
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - make -j2
- name: Test
  image: "${DRONE_REPO}:${DRONE_COMMIT:0:8}"
  commands:
  - cd build
  - ctest --verbose


volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock