kind: pipeline
type: docker
name: default

steps:
- name: Build Docker Image
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker build -t "inekf:${DRONE_COMMIT}" .
- name: Build
  image: inekf:*DRONE_COMMIT
  commands:
  - mkdir build
  - cd build
  - cmake .. -DEXAMPLES=OFF
  - make -j2
- name: Test
  image: inekf:*DRONE_COMMIT
  commands:
  - cd build
  - ctest --verbose


volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock