kind: pipeline
type: docker
name: default

steps:
- name: Install Eigen
  image: rikorose/gcc-cmake
  commands:
  - cd /
  - git clone https://gitlab.com/libeigen/eigen.git
  - cd eigen
  - mkdir build
  - cd build
  - cmake ..
  - make install
  - cd ../..
  - mkdir build
  - cd build
  - cmake .. -DPYTHON=OFF
  - make
  - make test