kind: pipeline
type: docker
name: test

steps:
- name: Build Docker Image
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker build -t "${DRONE_REPO}:${DRONE_COMMIT:0:8}" tests/
  
- name: Build
  image: "${DRONE_REPO}:${DRONE_COMMIT:0:8}"
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - make -j2
- name: Test
  image: "${DRONE_REPO}:${DRONE_COMMIT:0:8}"
  commands:
  - cd build
  - ctest --verbose

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: python

steps:
- name: docker
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker build -t "${DRONE_REPO}-python:${DRONE_COMMIT:0:8}" python/
  
- name: py36
  image: "${DRONE_REPO}-python:${DRONE_COMMIT:0:8}"
  commands:
  - PYTHON_VERSION=cp36-cp36m PLAT=manylinux2014_x86_64 bash python/build-wheels.sh
  depends_on:
  - docker

- name: py37
  image: "${DRONE_REPO}-python:${DRONE_COMMIT:0:8}"
  commands:
  - PYTHON_VERSION=cp37-cp37m PLAT=manylinux2014_x86_64 bash python/build-wheels.sh
  depends_on:
  - docker

- name: py38
  image: "${DRONE_REPO}-python:${DRONE_COMMIT:0:8}"
  commands:
  - PYTHON_VERSION=cp38-cp38 PLAT=manylinux2014_x86_64 bash python/build-wheels.sh
  depends_on:
  - docker

- name: py39
  image: "${DRONE_REPO}-python:${DRONE_COMMIT:0:8}"
  commands:
  - PYTHON_VERSION=cp39-cp39 PLAT=manylinux2014_x86_64 bash python/build-wheels.sh
  depends_on:
  - docker

- name: pypi_publish
  image: plugins/pypi
  when:
    event:
    - tag 
  settings:
    username:
      from_secret: pypi_username
    password:
      from_secret: pypi_password
    distributions:
    - bdist_wheel
    skip_build: true
  depends_on:
  - py36
  - py37
  - py38
  - py39

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
