kind: pipeline
type: docker
name: default

steps:
- name: Build
  image: contagon/inekf-deps
  commands:
  - mkdir build
  - cd build
  - cmake .. -DEXAMPLES=OFF
  - make -j2
- name: Test
  image: contagon/inekf-deps
  commands:
  - cd build
  - make test