kind: pipeline
type: docker
name: default

steps:
- name: Install Eigen
  image: rikorose/gcc-cmake
  commands:
  - git clone git@gitlab.com:libeigen/eigen.git
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install